version: '3.8'

services:
  specters:
    build: .
    
    
    container_name: specters
    ports:
      - "3000:3000"
    volumes:
      
      
      - /home:/app/managed/home:rw
      - /var/log:/app/managed/logs:ro
      
      
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    
    security_opt:
      - no-new-privileges:true
    
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
    
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  
  
  
  
  
  
  
  
  
